version: "3.9"

services:
  keycloak:
    image: keycloak/keycloak:26.4.6
    container_name: keycloak-local-dev
    hostname: keycloak.local
    ports:
      - "9090:8080"
    # The mem_limit is still a valid YAML field in Docker due to backward compatibility with v2.
    mem_limit: 2g
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://keycloak:8080
#      - KC_HTTP_RELATIVE_PATH=/auth
    volumes:
      - kc-v-data:/opt/keycloak/data
      - kc-v-providers:/opt/keycloak/providers
      - kc-v-log:/opt/keycloak/log
    command: ["start-dev"]
    networks:
      - orvix-local-dev-network
  postgres:
    image: postgres:latest
    container_name: orvix-postgres-local-dev
    environment:
      POSTGRES_DB: orvix-local-dev
      POSTGRES_USER: postgresql-orvix-local-dev
      POSTGRES_PASSWORD: postgresql-orvix-local-dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  orvix-gateway-local:
    image: borispopicdev/orvix-gateway:latest
    container_name: orvix-gateway-local
    hostname: orvix-gateway.local
    extra_hosts:
      - "host.docker.internal:host-gateway" # "host-gateway" is a special Docker value. Docker replaces it with the appropriate host-side gateway IP(e.g. an IP through which the container
                                            # can reach the Docker host, i.e. my notebook)
      - "downstream:host-gateway"
    ports:
      - "8081:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DOWNSTREAM_URI=http://downstream:8080
      - downstream.uri=http://downstream:8080
      - downstream.user.uri=http://orvix-user-local:8080
      - downstream.report.uri=http://orvix-report-local:8080
    networks:
      - orvix-local-dev-network
  orvix-user-local:
    image: borispopicdev/orvix-user:latest
    container_name: orvix-user-local
    hostname: orvix-user.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "downstream:host-gateway"
    ports:
      - "8082:8080"
      - "5006:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DOWNSTREAM_URI=http://downstream:8080
      - POD_NAME=docker-container-local-dev-orvix-user-local
      - POD_NAMESPACE=fake-docker-mock-namespace
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        export POD_IPAddr="$(hostname -i)"
        exec java -jar app.jar
    networks:
      - orvix-local-dev-network
  orvix-report-local:
    image: borispopicdev/orvix-report:latest
    container_name: orvix-report-local
    hostname: orvix-report.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "downstream:host-gateway"
    ports:
      - "8083:8080"
      - "5007:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      - DOWNSTREAM_URI=http://downstream:8080
      - POD_NAME=docker-container-local-dev-orvix-report-local
      - POD_NAMESPACE=fake-docker-mock-namespace
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        export POD_IPAddr="$(hostname -i)"
        exec java -jar app.jar
    networks:
      - orvix-local-dev-network

volumes:
  kc-v-data:
    name: kc-data
  kc-v-providers:
    name: kc-providers
  kc-v-log:
    name: kc-log
  postgres_data:

networks:
  orvix-local-dev-network:
    driver: bridge
