server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    kubernetes:
      client:
        namespace: dev
      discovery:
        enabled: true
        namespaces:
          - dev
        include-not-ready-addresses: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  info:
    env:
      enabled: true

info:
  app:
    name: Orvix Gateway
    version: 1.0.0
    description: Orvix Gateway microservice
